import type { LineageAnalysisResult } from '@/types/lineage'

function escapeCypher(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

function propLine(key: string, value: string | number | null | undefined): string | null {
  if (value === null || value === undefined || value === '') return null
  return typeof value === 'number' ? `  ${key}: ${value}` : `  ${key}: "${escapeCypher(String(value))}"`
}

/** 生成 Neo4j Cypher：target -[:DEPENDS_ON]-> source。 */
export function generateCypher(result: LineageAnalysisResult): string {
  const lines: string[] = [
    '// SQL lineage generated by SQL Viz',
    `// ${result.summary}`,
    '',
  ]

  for (const table of result.tables) {
    lines.push(`MERGE (t:Table {name: "${escapeCypher(table.name)}"})`)
    const props = [
      propLine('t.type', table.type),
      propLine('t.database', table.database),
      propLine('t.schema', table.schema),
      propLine('t.alias', table.alias),
    ].filter(Boolean)
    if (props.length > 0) lines.push('SET', props.join(',\n'))
    lines.push('')
  }

  for (const dep of result.dependencies) {
    const source = result.tables.find((table) => table.id === dep.source)?.name ?? dep.source
    const target = result.tables.find((table) => table.id === dep.target)?.name ?? dep.target
    lines.push(`MERGE (target:Table {name: "${escapeCypher(target)}"})`)
    lines.push(`MERGE (source:Table {name: "${escapeCypher(source)}"})`)
    const props = [
      propLine('kind', dep.kind),
      propLine('statementIndex', dep.statementIndex),
      propLine('description', dep.description),
    ].filter(Boolean)
    if (props.length > 0) {
      lines.push(`MERGE (target)-[:DEPENDS_ON {\n${props.join(',\n')}\n}]->(source);`)
    } else {
      lines.push('MERGE (target)-[:DEPENDS_ON]->(source);')
    }
    lines.push('')
  }

  return lines.join('\n')
}
